### ISSUE TITLE
Implement i18n translations

### ISSUE THREAD

**Issue by circlecube** [newfold-labs/wp-module-performance#12]
The default text strings are set up for translation strings.

The module needs a .pot file and associated .po, .mo and .json files for translations. The strings likely have pt_BR and es_MX translations already thanks to the Hostgator Plugin.

The module needs to contain the translations as well as load them for the module specific text-domain: `wp-module-performance` or update the text-domain to something newfold specific like `newfold-wp-module-performance`.

Refer to the onboarding module which has translations in place here: https://github.com/newfold-labs/wp-module-onboarding/pull/299

**Comment by arunshenoy99** [comment]
@circlecube closing this as we are moving it to JIRA. It will now be handled under https://jira.newfold.com/browse/PRESS7-139. Thanks!
